use_frameworks!

target 'GASocialLogin_Example' do
  
  pod 'GASocialLogin/Facebook', :path => '../'
  pod 'GASocialLogin/Google', :path => '../'
  

  target 'GASocialLogin_Tests' do
    inherit! :search_paths

    
  end
end
